### ISSUE TITLE
Road to v1.0

### ISSUE THREAD

**Issue by Cryrivers** [Cryrivers/manta-style#3]
# Manta Style Limitations
- [ ] `extends` keyword in `interface` declaration will be ignored
```ts
interface A extends B {
  key: string;
}
```
- [x] [Intersection type is not supported yet](/Cryrivers/manta-style/issues/11)
```ts
type A = B & { key: string };
```
- [x] [Built-in type helpers like `Exclude` and `Extract` are not supported yet](/Cryrivers/manta-style/issues/10)
# Unimplemented Features
- [x] [Support to read request params](/Cryrivers/manta-style/issues/9)
- [ ] [Snapshot generation for all endpoints / scenario (different combination of conditional types)](/Cryrivers/manta-style/issues/8)
- [ ] [Snapshot hot swapping](/Cryrivers/manta-style/issues/7)
- [x] [Config hot reloading](/Cryrivers/manta-style/issues/6)
- [x] [Selective API Mocking](/Cryrivers/manta-style/issues/5)
- [x] [Selective API Proxying with snapshot support](/Cryrivers/manta-style/issues/4)
# Considered
- Validation features (given up)
- Integration to JSONServer
- Babel + Flow transformers and builders
- Doc site generation
